### PR TITLE
Add support for use as a node module

### PR DESCRIPTION
**Pull request by ascorbic**
I have made some changes to this so that it can be used with a bundler such as Webpack or Parcel. I've documented how to do this. Currently the docs refer to the Git URL, but if you publish this to NPM then it will be a lot easier, plus it will allow you to load from UNPKG. It's ready for this: `npm publish` should work once you have an account set up.

### CODE REVIEW

**Comment by elmarquis** [comment]
Hi @ascorbic This is brilliant. Thanks so much for your efforts. Looking at this an a number of other things over the next week or so. Will update soon.

**Comment by ascorbic** [comment]
Great! It would be good if you could test this with your projects. It shouldn't cause any regressions, but I've only been using it with a bundler so some issues might creep in for people using script tags. I'd especially take some time to test it using UNPKG once you have published it to NPM. That could be a great way to distribute it.

**Comment by ascorbic** [comment]
I should add that I've also included some basic Typescript typings too.

**Comment by elmarquis** [comment]
Great, thanks. Will def give it a good test. Was a future plan to try get it up on NPM once I'd had time to figure it out, so thanks for helping me get there faster.

**Pull request merged**
